### ISSUE TITLE
ctrl+C not working well with lots of output

### ISSUE THREAD

**Issue by daviesalex** [liamg/darktile#155]
**Describe the bug**
ctrl+C often does not interrupt a long running command that produces output

**To Reproduce**
1. SSH to a box. Boxes that are further away (e.g. across an Ocean, ~100ms) will make this more obvious
2. Run a command that generates a lot of output (ls -l a directory with many files, cat a file, etc.)
3. Type Ctrl+C
4. Observe that it does not quickly stop printing output. (Compare with something like putty)

**Expected behavior**
Pressing ctrl+C should interrupt the output

**Comment by daviesalex** [comment]
I actually think this is a generic ctrl+c issue. Run a long running command and compare with putty:

![image](https://user-images.githubusercontent.com/1106249/51309861-408fbd80-1a3d-11e9-89c5-590c149c490e.png)

vs

![image](https://user-images.githubusercontent.com/1106249/51309878-47b6cb80-1a3d-11e9-98bc-b8e50f4e2750.png)

**Comment by MaxRis** [comment]
- In the way the issue is described it is rarely reproducible for me. I was able to see constantly the issue of "ctrl+c" ignoring by long lasting output generated by `ls -l` on directory with 100K files. All "ctrl+c" signals characters were appended after `ls -l` output was printed in terminal. Next days I was not able to repro this anymore (on any kind of remote machine - in Central US or local, on any kind of Aminal git revision).
- There is long delay issue(4-5 seconds) after pressing "ctrl+c" till the output interruption. On Linux with Aminal or using Putty the delay is around (1-2 seconds). Therefore the issue seems to be Windows related only.
- If to alter application source code and decrease amount operations to process and render each rune (redirect "compressed" output only to console), the delay of output termination is decreasing to 2-3 seconds (from 4-5 seconds). Current conclusion is that on Windows there is some delay of pseudo console output processing. It might be because of pipe's buffer between ConPTY output and Aminal's receiver, or processing of received runes on Windows happens slower than on *nix systems and because of that we experience visual delay in interruption till all symbols are rendered on the screen.
Further investigation is required.

**Comment by MaxRis** [comment]
Confirmed, ConPTY output on Windows 10 1903 build 18323.1000 works in 3 times faster than on 1809. The visual timeout after pressing "ctrl+c" till the interruption takes less than 2 seconds under "the heavy work-load":
```
2019/01/31 13:56:15 Processed 100000 runes in 49.8735ms
2019/01/31 13:56:15 Processed 100000 runes in 47.8646ms
2019/01/31 13:56:15 Processed 100000 runes in 49.8698ms
2019/01/31 13:56:15 Processed 100000 runes in 48.867ms
2019/01/31 13:56:15 Processed 100000 runes in 46.8743ms
2019/01/31 13:56:15 Processed 100000 runes in 46.8755ms
```

**Comment by MaxRis** [comment]
Interesting that `OSCTerminators: map[rune]struct{}{0x00: {}},` doesn't work on Windows 18323 anymore.

I've just tried with *nux terminators and that resolved all appeared issues. It looks like Windows Console team made some progress in compatibility as well.

**Comment by MaxRis** [comment]
Moving the Issue to Backlog. Hopefully, it should be fully resolved after jump into Windows 10 1903

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
