### ISSUE TITLE
Please support "real" buffer clearing, bound to a key, on Windows

### ISSUE THREAD

**Issue by cjw296** [liamg/darktile#195]
**Is your feature request related to a problem? Please describe.**
A really valuable feature for me on macOS Terminal is using Apple-k to clear the terminal and its scrollback buffer. This is particularly helpful for repeated runs of commands that generate a lot of output, to avoid getting confused between the output of two or more runs.

**Describe the solution you'd like**
Windows-k (but configurably bound) to totally clear the window and buffer and leave me with a fresh prompt.

**Describe alternatives you've considered**

None, really.

**Additional context**

None.

**Comment by rrrooommmaaa** [comment]
@cjw296 I'm making it configurable all right, I can also configure the default of "super + k", but the problem is: Windows + k keystroke gets intercepted by Windoes 10 and doesn't pass through (at least on my laptop which only has right Win key).
Can we agree on "ctrl + shift + k" to be default? And then anyone can experiment with "super + k", if needed

**Comment by cjw296** [comment]
I'd prefer a single modifier key if possible. What's alt-k bound to?

**Comment by rrrooommmaaa** [comment]
@cjw296 If you prefer alt+k, then you can set it up, no problem. But it's not a good idea to make it default because all alt+letter keystrokes get forwarded to underlying unix shell. Bash and others handle some of them (not usre about alt+k), for example: https://www.howtogeek.com/howto/ubuntu/keyboard-shortcuts-for-bash-command-shell-for-ubuntu-debian-suse-redhat-linux-etc/

**Comment by MaxRis** [comment]
Feature should appear in the next nightly-develop build

**Comment by mjs** [comment]
It seems this has been done. Can it be closed?

**Comment by cjw296** [comment]
I haven't had a chance to test, if you can confirm that it's working like Apple-K does in a macOS terminal window, then please feel free to close.

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
