### ISSUE TITLE
tmux is not displayed correctly when running under mosh

### ISSUE THREAD

**Issue by maxhora** [liamg/darktile#204]
**Describe the bug**
tmux rendered with strange glitches if running under mosh.exe

**To Reproduce**
1. mosh.exe -l USER HOST
2. tmux
3. bottom bar is get overlapped with terminal commands output; others strange rendering glitches

**Environment (please complete the following information):**
 - OS + Version: Windows 1809
 - Shell: cmd.exe/mosh.exe/tmux

mosh.exe and mosh-client.exe is attached.
[aminal-mosh-windows-2019-02-07.zip](https://github.com/liamg/aminal/files/2842200/aminal-mosh-windows-2019-02-07.zip)

**Comment by MaxRis** [comment]
It's turned out that the experienced issue is related to extra new line character inserted by ConPTY's internals. Issue with detailed reproducible description reported to MS Console team https://github.com/Microsoft/console/issues/380

Meanwhile, it's supposed to use custom build of mosh-client.exe with workaround to generate console output 1 column shorter than it is to avoid odd ConPTY behavior. 
[mosh-build-2019-02-27.zip](https://github.com/liamg/aminal/files/2923678/mosh-build-2019-02-27.zip)

Moving the issue to Backlog

**Comment by MaxRis** [comment]
MS Console Team helped to figure out that `tmux` issue happens because vt processing is OFF on mosh-client.exe side. Currently `mosh-client.exe` is built based on MSYS2 toolchain and it seems it has impact of how data goes to std output stream. I was not able to turn vt processing ON directly in mosh-client.exe, but if writing to std stream happens from mosh.exe built with GoLang MinGW based toolchain the issue doesn't happen.
Current direction is to move mosh-client sources to be built under GoLang MinGW toolchain to have native integration with Aminal. This issue shoudn't appear with such solution.

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
