### ISSUE TITLE
Duplicated lines in backscroll when resizing the Aminal window

### ISSUE THREAD

**Issue by vadymeng0** [liamg/darktile#270]
When resizing the Aminal window, it looks like some lines on the top of the terminal buffer are doubling so that it is possible to scroll the window up and see the duplicates. The number of doubled lines seems to depend on how small the window is made. This behavior is reproduced on Windows, and not on Debian. Not tested on MacOS.

**To Reproduce**
1. Run Aminal as usual. The two-lines greeting message from Windows `cmd.exe` will be displayed.
2. Try to scroll the window with the mouse wheel. It shouldn't scroll (because there are no scrollback lines)
2. Resize the Aminal's window to make it display less than 10 lines. The two-lines greeting message should be still on the screen.
3. Try to scroll the window with the mouse wheel again. The window will be scrolled showing duplicate lines.

**Expected behavior**
There must be no duplicate lines on resizing the window.

**Environment (please complete the following information):**
 - `Windows` only (on `Debian` was not able to reproduce, on `MacOS` did not test

**Comment by nikitar020** [comment]
So, it looks like that, with current ConPTY implementation it is not possible to correctly handle resizing of the window when backscroll is enabled. This is because right after resizing, the system tries to re-draw the screen by sending the whole contents of the pseudo console, line by line, even after the window is actually resized. 

See this issue for additional info: https://github.com/Microsoft/console/issues/383

**Comment by rrrooommmaaa** [comment]
@nikitar020 In `develop` branch, there is a method (pty *winConPty)  Clear() that shows how to fill the output screen buffer with arbitrary data. It fills it with "emptiness" but you can write a method that fills with appropriate data that should be there after resizing.

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
