### ISSUE TITLE
Scrollbar

### ISSUE THREAD

**Issue by iangudger** [liamg/darktile#89]
When an application produces a lot of output, it is helpful to be able to quickly scroll back. In many cases, even page up/page down are too slow. An optional scrollbar is one way to solve this problem.

**Comment by thagoat** [comment]
+1

**Comment by nieware** [comment]
another way to solve the problem would be a "minimap" at the right side of the window like in Sublime Text or Terminology (where it's called "miniview"). This would have more functionality and may be actually easier to implement, because with scrollbars people have very different (usually higher) expectations. 

However, if someone actually implements this, please don't make the same mistake as Terminology - there the "miniview" currently overlaps the output.

**Comment by liamg** [comment]
I'm 100% on board with @nieware on this one.

**Comment by MarcelWalk** [comment]
Remember to hide it when not needed, since currently it is always visible

**Comment by liamg** [comment]
Closed due to complete rewrite as part of bringing the project back to life, please create a new issue if still relevant. Thank you!
